signbank/video/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.urls import path

# Views
from . import views

# Application namespace
app_name = 'video'

urlpatterns = [
    path('<int:videoid>/', views.video_view, name='glossvideo'),
    path('poster/<int:videoid>', views.poster_view, name='glossvideo_poster'),
    path('upload/', views.upload_glossvideo_view, name='upload_glossvideo'),
    path('upload/gloss/', views.upload_glossvideo_gloss_view,
         name='upload_glossvideo_gloss'),
    path('upload/recorded/', views.add_recorded_video_view,
         name='add_recorded_video'),
    # View to upload multiple videos with no foreign key to gloss.
    path('add/', views.addvideos_formview, name='upload_videos'),
    # View that shows a list of glossvideos with no foreign key to gloss, user can add fk to gloss for glossvideos.
    path('uploaded/', views.uploaded_glossvideos_listview, name='manage_videos'),
    # View that updates a glossvideo
    path('update/', views.update_glossvideo_view, name='glossvideo_update'),
    # View that handles the upload of poster file
    path('add/poster', views.add_poster_view, name='add_poster'),
    # Change priority of video
    path('order/', views.change_glossvideo_order,
         name='change_glossvideo_order'),
    # Change publicity of video
    path('publicity/', views.change_glossvideo_publicity,
         name='change_glossvideo_publicity'),

    path('csv', views.export_glossvideos_csv, name='export_glossvideos_csv')
]

signbank/video/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms

from .models import GlossVideo
from signbank.dictionary.models import Dataset, Gloss


class GlossVideoForm(forms.ModelForm):
    """Form for GlossVideo."""
    def __init__(self, *args, **kwargs):
        super(GlossVideoForm, self).__init__(*args, **kwargs)
        # Form is used in gloss creation, support creating a gloss without a video.
        self.fields['videofile'].required = False

    def clean_videofile(self):
        # Checking here that the file ends with .mp4
        if self.cleaned_data['videofile'] and not self.cleaned_data['videofile'].name.endswith('.mp4'):
            raise forms.ValidationError('File is not a mp4. Please upload only mp4 files')
        return self.cleaned_data['videofile']

    class Meta:
        model = GlossVideo
        fields = ["title", "videofile"]


class GlossVideoForGlossForm(forms.ModelForm):
    """Form for GlossVideo with Gloss."""
    redirect = forms.CharField(widget=forms.HiddenInput, required=False)
    webcam = forms.BooleanField(required=False)

    class Meta:
        model = GlossVideo
        fields = ["title", "videofile", "gloss"]


class GlossVideoUpdateForm(forms.ModelForm):
    """Form for adding Gloss and Dataset to GlossVideo."""
    gloss = forms.ModelChoiceField(queryset=Gloss.objects.none(), widget=forms.TextInput)

    class Meta:
        model = GlossVideo
        fields = ['dataset', 'videofile', 'gloss']




class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True
    attrs={'multiple': True, 'onchange': 'updateSize();'}

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = [single_file_clean(data, initial)]
        return result

class MultipleVideoUploadForm(forms.Form):
    """Form for uploading multiple videos."""
    allow_multiple_selected = True
    file_field = MultipleFileField()
    dataset = forms.ModelChoiceField(queryset=Dataset.objects.all(), required=True, empty_label=None)

    def clean_file_field(self):
        data = self.cleaned_data['file_field']
        return data


class GlossVideoPosterForm(forms.ModelForm):
    class Meta:
        model = GlossVideo
        fields = ['posterfile', 'id']

signbank/video/templates/addvideos.html
{% extends "baselayout.html" %}
{% load i18n %}
{% block bootstrap3_title %}{% blocktrans %}Upload Videos{% endblocktrans %} | {% endblock %}

{%block extrahead %}
<script>
function updateSize() {
  var nBytes = 0,
      oFiles = document.getElementById("id_file_field").files,
      nFiles = oFiles.length;
  for (var nFileId = 0; nFileId < nFiles; nFileId++) {
    nBytes += oFiles[nFileId].size;
  }
  var sOutput = nBytes + " bytes";
  // optional code for multiples approximation
  for (var aMultiples = ["KiB", "MiB", "GiB", "TiB", "PiB", "EiB", "ZiB", "YiB"], nMultiple = 0, nApprox = nBytes / 1024; nApprox > 1; nApprox /= 1024, nMultiple++) {
    sOutput = nApprox.toFixed(3) + " " + aMultiples[nMultiple] + " (" + nBytes + " bytes)";
  }
  // end of optional code
  document.getElementById("fileNum").innerHTML = nFiles;
  document.getElementById("fileSize").innerHTML = sOutput;
}
</script>
{% endblock %}
{% block content %}
<div class="page-header">
  <h2>{% blocktrans %}Upload videos{% endblocktrans %} <small>{% blocktrans %}You can select multiple videos to be uploaded at once{% endblocktrans %}</small></h2>
</div>
<div>
    <form enctype="multipart/form-data" name="uploadvideos" method="post">
        {% csrf_token %}
        <label for="id_dataset">{% blocktrans %}Dataset{% endblocktrans %}:</label>
        <p>{{form.dataset}}</p>
        <label for="id_file_field">{% blocktrans %}File{% endblocktrans %}:</label>
        <p><input id="id_file_field" name="file_field" onchange="updateSize();" multiple="" type="file"> {% blocktrans %}selected files{% endblocktrans %}: <span id="fileNum">0</span>; {% blocktrans %}total size{% endblocktrans %}: <span id="fileSize">0</span></p>
        <p><input type="submit" value="{% blocktrans %}Send file(s){% endblocktrans %}"></p>
    </form>
</div>
{% endblock %}

signbank/video/templates/uploaded_glossvideos.html
{% extends "baselayout.html" %}
{% load i18n %}
{% load static %}
{% block bootstrap3_title %}{% blocktrans %}Manage Uploaded Videos{% endblocktrans %} | {% endblock %}
{% block extrahead %}
<link rel="stylesheet" href="{% static "css/jquery-ui/jquery-ui.min.css" %}">
{% endblock %}
{% block content %}
<div class="page-header">
  <h2>{% blocktrans %}Manage Uploaded Videos{% endblocktrans %} <small>{% blocktrans %}Connect Glossvideos to Glosses{% endblocktrans %}</small></h2>
</div>
<div id="dataset" class="panel panel-default">
    <div class="panel-body">
        <form id="dataset-select">
            <h3><span class="label label-danger">{% blocktrans %}Select the dataset you want to work with!{% endblocktrans %}</span></h3>
            <label for="id_dataset"><strong>{% blocktrans %}Dataset{% endblocktrans %}:</strong></label>
            {{form.dataset}}
            <input class='btn btn-primary' type='submit' value='{% blocktrans %}Ok{% endblocktrans %}'>
        </form>
    </div>
</div>
<div class="pagination">
    <span class="step-links">
        <ul class="pagination pagination-sm">
        {% if page_obj.has_previous %}{# Insert dataset from request #}
            <li><a href="?page={{ page_obj.previous_page_number }}&dataset={{request.GET.dataset}}">&laquo; {% blocktrans %}previous{% endblocktrans %}</a>
        {% endif %}
        {% for curpage in page_obj.paginator.page_range %}
            <li{% if curpage == page_obj.number %} class="active"{% endif %}><a href="?page={{ curpage }}&dataset={{request.GET.dataset}}">{{ curpage }}</a>
        {% endfor %}
        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}&dataset={{request.GET.dataset}}">{% blocktrans %}next{% endblocktrans %} &raquo;</a>
        {% endif %}
        </ul>
        <p>{% blocktrans %}Total of{% endblocktrans %} {{ page_obj.paginator.count }} {% blocktrans %}videos{% endblocktrans %}.</p>
    </span>
</div>
<div id="glossvideos" class="row">
{% for video in videos %}
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">{{video.videofile}}</div>
            <div class="panel-body">
            <form id="glossvideo{{video.pk}}" class="video-form" method="POST" action="{% url 'video:glossvideo_update' %}">
                {% csrf_token %}
                <input type="hidden" name="glossvideo" class="glossvideo-pk" value="{{video.pk}}">
                <div id="videocontainer">
                    <div class="player">
                        <video id="{{video.pk}}" width="450" preload="metadata" controls muted>
                            {% if video.get_extension == '.mp4' %}
                            <source src="{{video.videofile.url}}" type="video/mp4">
                            {% elif video.get_extension == '.webm' %}
                            <source src="{{video.videofile.url}}" type="video/webm">
                            {% endif %}
                            {% blocktrans %}Your browser does not support the video tag.{% endblocktrans %}
                        </video>
                    </div>
                </div>
                <div class="ui-widget">
                    <label for="id_gloss"><strong>{% blocktrans %}Gloss{% endblocktrans %}:</strong></label>
                    <input name="gloss" required="" id="id_gloss" class="gloss-autocomplete" type="text">

                    <input class="btn btn-primary" type="submit" value="{% blocktrans %}Save{% endblocktrans %}">
                </div>
            </form>
            </div>
        </div>
    </div>
{% endfor %}
</div>
<div style="text-align:center;">
    <button type="button" id="update-multiple-videos" class="btn btn-info btn-lg" style="margin-bottom:15px;" onclick="updateVideos()">
        {%blocktrans%}Save all{%endblocktrans%}</button>
</div>
{% endblock %}
{% block extrajs %}
<script src="{% static "js/jquery-ui.min.js" %}"></script>
<script>
  $( function() {
    var availableTags = [{% for g in gloss_choices %}{label:"{{g.idgloss}}", value:"{{g.id}}"},{% endfor %}];
    $( ".gloss-autocomplete" ).autocomplete({
      source: availableTags
    });
  } );
</script>
<script>
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});

// This script is used to save multiple instances at once with ajax.
function updateVideos(){
    var forms = document.getElementsByClassName("video-form");
    var updatelist = [];
    var formlist = [];
    for (var i=0; i<forms.length; i++){
        var selected = forms[i].getElementsByClassName("gloss-autocomplete")[0];
        // Only update the ones that don't have empty value.
        if (selected.value != "") {
            var glossvideo = forms[i].getElementsByClassName("glossvideo-pk")[0];
            // These will be saved, as they have a value set.
            updatelist.push({"glossvideo": glossvideo.value, "gloss": selected.value});
            // Add the current form to be "removed" from the page.
            formlist.push(forms[i]);
        }
    }
    // Send ajax post request.
    $.ajax({url: "/video/update/", type: "post", contentType: "application/json", context:{"forms":formlist},
      data:JSON.stringify({"updatelist": updatelist, "csrfmiddlewaretoken": csrftoken, "ajax": "true"})
     })
     .done(function() {
        forms = this.forms;
        for (var i=0; i<forms.length; i++){
            // Set the selected value empty, to make it empty even on soft refresh.
            var selected = "";
            // Only update the ones that don't have empty value.
            if (selected.value != "") {
                forms[i].getElementsByClassName("gloss-autocomplete")[0].value = "";
                var alert = document.createElement("div");
                alert.className = "alert alert-success";
                alert.innerHTML = "{%blocktrans%}GlossVideo successfully updated!{%endblocktrans%}";
                forms[i].parentNode.appendChild(alert);
                forms[i].parentNode.removeChild(forms[i]);
            }
        }
    })
    .fail(function(jqXHR, textStatus, errorThrown) {
        alert(errorThrown+"("+textStatus+"): {% blocktrans %}Did you provide all values as id numbers?{% endblocktrans %}");
    });
}
</script>
{% endblock %}

signbank/video/templates/videos_with_no_gloss.html
{% extends "baselayout.html" %}
{% load i18n %}
{% block content %}
<div class="page-header">
  <h2>{% blocktrans %}Videos with no gloss{% endblocktrans %} <small>{% blocktrans %}You can add a gloss for each video{% endblocktrans %}</small></h2>
</div>
<div id="dataset" class="panel panel-default">
    <div class="panel-body">
        <form id="dataset-select">
            <h3><span class="label label-danger">{% blocktrans %}Select the dataset you want to work with!{% endblocktrans %}</span></h3>
            <label for="id_dataset"><strong>{% blocktrans %}Dataset{% endblocktrans %}:</strong></label>
            {{form.dataset}}
            <input class='btn btn-primary' type='submit' value='{% blocktrans %}Ok{% endblocktrans %}'>
        </form>
    </div>
</div>
<div id="glossvideos" class="row">
{% for video in videos %}
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">{{video.videofile}}</div>
            <div class="panel-body">
            <form id="glossvideo{{video.pk}}" method="POST" action="/video/update/">
                {% csrf_token %}
                <input type="hidden" name="glossvideo" value="{{video.pk}}">
                <div id="videocontainer">
                    <div class="player">
                        <video id="{{video.pk}}" width="450" preload="metadata" controls muted>
                            <source src="{{ STATIC_URL }}{{video.videofile|urlencode}}" type="video/mp4">
                            {% blocktrans %}Your browser does not support the video tag.{% endblocktrans %}
                        </video>
                    </div>
                </div>
                <div>
                    <label for="id_gloss"><strong>{% blocktrans %}Gloss{% endblocktrans %}:</strong></label>
                    {{form.gloss}}
                    <input class='btn btn-primary' type='submit' value='{% blocktrans %}Save{% endblocktrans %}'>
                </div>
            </form>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="pagination">
    <span class="step-links">
        <ul class='pagination pagination-sm'>
        {% if page_obj.has_previous %}{# Insert dataset from request #}
            <li><a href="?page={{ page_obj.previous_page_number }}&dataset={{request.GET.dataset}}">&laquo; {% blocktrans %}previous{% endblocktrans %}</a>
        {% endif %}
            <li><span class="current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}&dataset={{request.GET.dataset}}">{% blocktrans %}next{% endblocktrans %} &raquo;</a>
        {% endif %}
        </ul>
    </span>
</div>
{% endblock %}