signbank/dictionary/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path
from django.views.generic.base import RedirectView

# Views
from . import adminviews, delete, publicviews, update, views

# Application namespace
app_name = 'dictionary'

urlpatterns = [
    # Public views for dictionary
    path('', publicviews.GlossListPublicView.as_view(), name='public_gloss_list'),
    path('gloss/<int:pk>', publicviews.GlossDetailPublicView.as_view(),
         name='public_gloss_view'),
    # Support old URLs, redirect them to new URLs.
    path('public/gloss/',
         RedirectView.as_view(pattern_name='dictionary:public_gloss_list', permanent=False)),
    path('public/gloss/<int:pk>',
         RedirectView.as_view(pattern_name='dictionary:public_gloss_view', permanent=False)),

    # Advanced search page
    path('advanced/', permission_required('dictionary.search_gloss')
         (adminviews.GlossListView.as_view()), name='admin_gloss_list'),

    # Main views for dictionary search page and gloss detail page, these used to be 'admin' views
    path('advanced/list/', permission_required('dictionary.search_gloss')
         (adminviews.GlossListView.as_view())),
    path('advanced/gloss/<int:pk>', permission_required('dictionary.search_gloss')
         (adminviews.GlossDetailView.as_view()), name='admin_gloss_view'),

    # GlossRelation search page
    path('advanced/glossrelation/', permission_required('dictionary.search_gloss')
         (adminviews.GlossRelationListView.as_view()), name='search_glossrelation'),
    # Redirect old URL
    path('search/glossrelation/', permission_required('dictionary.search_gloss')
         (RedirectView.as_view(pattern_name='dictionary:search_glossrelation', permanent=False))),

    # Manage lexicons
    path('lexicons/', login_required(views.ManageLexiconsListView.as_view()),
         name='manage_lexicons'),
    # Apply for lexicon permissions
    path('lexicons/apply/', login_required(views.ApplyLexiconPermissionsFormView.as_view()),
         name='apply_lexicon_permissions'),

    # Create
    path('advanced/gloss/create/', views.create_gloss, name='create_gloss'),

    # Urls used to update data
    path('update/gloss/<int:glossid>',
         update.update_gloss, name='update_gloss'),
    path('update/tag/<int:glossid>',
         update.add_tag, name='add_tag'),
    path('update/relation/',
         update.add_relation, name='add_relation'),
    path('update/relationtoforeignsign/',
         update.add_relationtoforeignsign, name='add_relationtoforeignsign'),
    path('update/morphologydefinition/',
         update.add_morphology_definition, name='add_morphologydefinition'),
    path('update/glossrelation/',
         update.gloss_relation, name='add_glossrelation'),

    path('advanced/delete/glossurl/<int:glossurl>',
         delete.glossurl, name='delete_glossurl'),

    path('update/lemma/<int:glossid>',
         update.add_lemma, name='add_lemma'),


    # CSV import urls
    path('advanced/import/csv/',
         update.import_gloss_csv, name='import_gloss_csv'),
    path('advanced/import/csv/confirm/',
         update.confirm_import_gloss_csv, name='confirm_import_gloss_csv'),

    # AJAX urls
    path('ajax/keyword/<str:prefix>',
         views.keyword_value_list),
    path('ajax/gloss/<str:prefix>',
         adminviews.gloss_ajax_complete, name='gloss_complete'),
    path('ajax/searchresults/',
         adminviews.gloss_ajax_search_results, name='ajax_search_results'),

    # XML ecv (externally controlled vocabulary) export for ELAN
    path('ecv/<int:dataset_id>',
         adminviews.gloss_list_xml, name='gloss_list_xml'),
    # Public ECV's
    path('public-ecv/<int:dataset_id>',
         publicviews.public_gloss_list_xml, name='public_gloss_list_xml'),

    path('csv/<int:dataset_id>',
         permission_required('dictionary.search_gloss')(adminviews.gloss_list_csv), name='gloss_list_csv'),

    # Network Graph of GlossRelations
    path('network-graph/',login_required(views.network_graph), name='network_graph'),
]

signbank/dictionary/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ObjectDoesNotExist
from django.db.utils import OperationalError, ProgrammingError

from tagging.models import Tag

from .models import Dataset, Language, SignLanguage, AllowedTags, GlossRelation, Gloss, Relation, \
    RelationToForeignSign, MorphologyDefinition,  FieldChoice, GlossURL


class GlossCreateForm(forms.ModelForm):
    """
    Form for creating a new gloss.
    This form also overrides the ModelForm validations.
    """
    dataset = forms.ModelChoiceField(label=_('Dataset'), required=True, queryset=Dataset.objects.all(), empty_label=None)
    try:
        qs = AllowedTags.objects.get(content_type=ContentType.objects.get_for_model(Gloss)).allowed_tags.all()
    except (ObjectDoesNotExist, OperationalError, ProgrammingError):
        qs = Tag.objects.all()
    tag = forms.ModelChoiceField(queryset=qs, required=False, empty_label="---", to_field_name='name',
                                 widget=forms.Select(attrs={'class': 'form-control'}))

    def clean_idgloss(self):
        """Validates that idgloss is unique in Dataset."""
        try:
            gloss = Gloss.objects.get(idgloss__exact=self.cleaned_data['idgloss'], dataset=self.cleaned_data['dataset'])
        except Gloss.DoesNotExist:
            return self.cleaned_data['idgloss']
        raise forms.ValidationError(
            # Translators: exception ValidationError
            _('This Gloss value already exists in the chosen Dataset. Please choose another value for Gloss.'),
            code='not_unique')

    class Meta:
        model = Gloss
        fields = ['dataset', 'idgloss', 'idgloss_en', ]


class TagUpdateForm(forms.Form):
    """Form to add a new tag to a gloss"""
    try:
        qs = AllowedTags.objects.get(content_type=ContentType.objects.get_for_model(Gloss)).allowed_tags.all()
    except (ObjectDoesNotExist, OperationalError, ProgrammingError):
        qs = Tag.objects.all()
    tag = forms.ModelChoiceField(queryset=qs, empty_label=None, to_field_name='name',
                                 widget=forms.Select(attrs={'class': 'form-control'}))


class TagDeleteForm(forms.Form):
    """Form to delete a tag from a gloss"""
    tag = forms.ModelChoiceField(queryset=Tag.objects.all(), empty_label=None, to_field_name='name')
    delete = forms.BooleanField(required=True, widget=forms.HiddenInput)


class TagsAddForm(forms.Form):
    """Form to add a new tags to a gloss"""
    try:
        qs = AllowedTags.objects.get(content_type=ContentType.objects.get_for_model(Gloss)).allowed_tags.all()
    except (ObjectDoesNotExist, OperationalError, ProgrammingError):
        qs = Tag.objects.all()
    tags = forms.ModelMultipleChoiceField(label=_('Tags'), queryset=qs, to_field_name='name')


ATTRS_FOR_FORMS = {'class': 'form-control'}


class GlossSearchForm(forms.ModelForm):
    # Translators: GlossSearchForm label
    dataset = forms.ModelMultipleChoiceField(label=_('Dataset'), queryset=Dataset.objects.all(), required=False)
    # Translators: GlossSearchForm label
    signlanguage = forms.ModelMultipleChoiceField(label=_('Sign language'), queryset=SignLanguage.objects.all(),
                                                  required=False)

    search = forms.CharField(label=_("Search"))
    # Translators: GlossSearchForm label
    gloss = forms.CharField(label=_("Gloss"))
    # Translators: GlossSearchForm label
    idgloss_en = forms.CharField(label=_("Gloss in English"))
    # Translators: GlossSearchForm label
    keyword = forms.CharField(label=_('Translations'))
    # Translators: GlossSearchForm label
    trans_lang = forms.ModelChoiceField(required=False, empty_label=_('Choose language'), queryset=Language.objects.all())

    try:
        qs = AllowedTags.objects.get(content_type=ContentType.objects.get_for_model(Gloss)).allowed_tags.all()
    except (ObjectDoesNotExist, OperationalError, ProgrammingError):
        qs = Tag.objects.all()
    tags = forms.ModelMultipleChoiceField(queryset=qs, required=False)
    nottags = forms.ModelMultipleChoiceField(queryset=qs)

    published = forms.BooleanField(label=_('Is published'), required=False)

    # Translators: GlossSearchForm label
    hasvideo = forms.BooleanField(label=_('Has videos'), required=False)
    hasnovideo = forms.BooleanField(label=_('No videos'), required=False)
    multiplevideos = forms.BooleanField(label=_('Multiple videos'), required=False)

    # These have been disabled until they are later needed
    # TODO: To enable these, uncomment them.
    """
    # Translators: GlossSearchForm label
    relation = forms.CharField(
        label=_('Search for gloss of related signs'), widget=forms.TextInput(attrs=ATTRS_FOR_FORMS))
    # Translators: GlossSearchForm label
    relationToForeignSign = forms.CharField(
        label=_('Search for gloss of foreign signs'), widget=forms.TextInput(attrs=ATTRS_FOR_FORMS))
    # Translators: GlossSearchForm label
    morpheme = forms.CharField(
        label=_('Search for gloss with this as morpheme'), widget=forms.TextInput(attrs=ATTRS_FOR_FORMS))

    # Translators: GlossSearchForm label
    phonology_other = forms.CharField(
        label=_('Phonology other'), widget=forms.TextInput())

    # Translators: GlossSearchForm label
    hasRelationToForeignSign = forms.ChoiceField(label=_('Related to foreign sign or not'), choices=[
        (0, '---------'), (1, _('Yes')), (2, _('No'))], widget=forms.Select(attrs=ATTRS_FOR_FORMS))
    # Translators: GlossSearchForm label
    hasRelation = forms.ChoiceField(
        label=_('Type of relation'), choices=RELATION_ROLE_CHOICES, widget=forms.Select(attrs=ATTRS_FOR_FORMS))
    # Translators: GlossSearchForm label
    hasMorphemeOfType = forms.ChoiceField(
        label=_('Has morpheme type'), choices=MORPHEME_ROLE_CHOICES, widget=forms.Select(attrs=ATTRS_FOR_FORMS))

    # Translators: GlossSearchForm label
    repeated_movement = forms.ChoiceField(
        label=_('Repeating Movement'), choices=NULLBOOLEANCHOICES)
    # ,widget=forms.Select(attrs=ATTRS_FOR_FORMS));
    # Translators: GlossSearchForm label
    alternating_movement = forms.ChoiceField(
        label=_('Alternating Movement'), choices=NULLBOOLEANCHOICES)
    """

    class Meta:
        ATTRS_FOR_FORMS = {'class': 'form-control'}

        model = Gloss
        fields = ('idgloss', 'idgloss_en', 'dialect', 'strong_handshape', 'weak_handshape', 'location',
                  'handedness', 'notes', 'relation_between_articulators', 'absolute_orientation_palm',
                  'absolute_orientation_fingers', 'relative_orientation_movement', 'relative_orientation_location',
                  'orientation_change', 'handshape_change', 'repeated_movement', 'alternating_movement',
                  'movement_shape', 'movement_direction', 'movement_manner', 'contact_type', 'mouth_gesture',
                  'mouthing', 'phonetic_variation', 'iconic_image', 'named_entity', 'semantic_field',
                  'number_of_occurences',)


class GlossRelationSearchForm(forms.Form):
    # Translators: GlossSearchForm label
    dataset = forms.ModelMultipleChoiceField(label=_('Dataset'), queryset=Dataset.objects.all(), required=False)
    search = forms.CharField(label=_("Search"))
    # Translators: GlossSearchForm label
    source = forms.CharField(label=_("Source Gloss"))
    # Translators: GlossSearchForm label
    target = forms.CharField(label=_("Target Gloss"))

    try:
        qs = AllowedTags.objects.get(content_type=ContentType.objects.get_for_model(GlossRelation)).allowed_tags.all()
    except (ObjectDoesNotExist, OperationalError, ProgrammingError):
        qs = Tag.objects.all()
    tags = forms.ModelMultipleChoiceField(queryset=qs, required=False, label=_("Relation type"))

    class Meta:
        ATTRS_FOR_FORMS = {'class': 'form-control'}


class GlossRelationForm(forms.Form):
    dataset = forms.ModelChoiceField(label=_("Lexicon"), queryset=Dataset.objects.all(), empty_label=None)
    source = forms.CharField(widget=forms.HiddenInput())
    target = forms.CharField(label=_("Gloss"), widget=forms.TextInput(attrs={'class': 'glossrelation-autocomplete'}))
    try:
        qs = AllowedTags.objects.get(content_type=ContentType.objects.get_for_model(GlossRelation)).allowed_tags.all()
    except (ObjectDoesNotExist, OperationalError, ProgrammingError):
        qs = Tag.objects.all()
    tag = forms.ModelChoiceField(label=_("Relation type:"),
                                 queryset=qs,
                                 required=True, to_field_name='name',
                                 widget=forms.Select(attrs={'class': 'form-control'}))
    delete = forms.IntegerField(required=False, widget=forms.HiddenInput())


class GlossURLForm(forms.ModelForm):
    class Meta:
        model = GlossURL
        fields = ["gloss", "url"]


class RelationForm(forms.ModelForm):
    # Translators: RelationForm label
    sourceid = forms.CharField(label=_('Source Gloss'))
    # Translators: RelationForm label
    targetid = forms.CharField(label=_('Target Gloss'))
    # Note that to_field_name has to be unique!
    role = forms.ModelChoiceField(label=_('Type'), queryset=FieldChoice.objects.filter(field='MorphologyType'),
                                  to_field_name='machine_value', empty_label=None,
                                  widget=forms.Select(attrs=ATTRS_FOR_FORMS))

    class Meta:
        model = Relation
        fields = ['role']
        widgets = {
            'role': forms.Select(attrs={'class': 'form-control'}),
        }


class RelationToForeignSignForm(forms.ModelForm):
    # Translators: RelationToForeignSignForm label
    sourceid = forms.CharField(label=_('Source Gloss'))
    # loan = forms.CharField(label='Loan')
    # Translators: RelationToForeignSignForm label

signbank/dictionary/templates/dictionary/admin_glossrelation_list.html
{% extends "baselayout.html" %}
{% load bootstrap3 %}
{% load i18n %}
{% load static %}
{# Translators: Title for GlossRelation search page #}
{% block bootstrap3_title %}{% blocktrans %}Search Gloss Relations{% endblocktrans %} | {% endblock %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/jquery-ui/jquery-ui.min.css' %}">
{% endblock %}
{% block extrajs %}
<script>
// http://www.javascript-coder.com/javascript-form/javascript-reset-form.phtml
function clearForm(myFormElement) {

  var elements = myFormElement.elements;

  myFormElement.reset();

  for(i=0; i<elements.length; i++) {

      field_type = elements[i].type.toLowerCase();

      switch(field_type) {

        case "text":
        case "password":
        case "textarea":
        case "hidden":

          elements[i].value = "";
          break;

        case "radio":
        case "checkbox":
            if (elements[i].checked) {
              elements[i].checked = false;
          }
          break;

        case "select-one":
        case "select-multiple":
                    elements[i].selectedIndex = -1;
          break;

        default:
          break;
      }
    }
    return(false);
}
</script>

<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/video-tooltip.js' %}"></script>

{% endblock %}
{% block content %}

{# Translators: admin_gloss_list header #}
<h2>{% blocktrans %}Search Relations of Glosses{% endblocktrans %}</h2>
<div id='searchformwell' class='well well-sm'>
    <form name='adminsearch' id='adminsearch'>
        <div class="container-fluid">
            <div class="row">

                <div class="col-md-2 col-sm-6 searchinput">
                    {% bootstrap_label searchform.dataset.label %}
                    {% bootstrap_field searchform.dataset show_label=False bound_css_class="not-bound" %}
                </div>
                <div class="col-md-5 col-sm-6 searchinput">
                    <div class="col-md-12 searchinput">
                        <div class='input-group'>
                            <label class='input-group-addon' for='id_search'>{{searchform.search.label}}</label>
                            <input id="id_search" name='search' class='form-control'
                                   {% if searchform.search.value %}value='{{searchform.search.value}}' {% endif %}
                                   placeholder='{% blocktrans %}Source or target gloss contains string{% endblocktrans %}'>
                        </div>
                    </div>

                    <div class="col-md-12 searchinput">
                        <div class='input-group'>
                            <label class='input-group-addon' for='id_glossrelation_source'>{{searchform.source.label}}</label>
                            <input id="id_glossrelation_source" name='source' class='form-control'
                                   {% if searchform.source.value %}value='{{searchform.source.value}}' {% endif %}
                                   placeholder='{% blocktrans %}Begins with string{% endblocktrans %}'>
                        </div>
                    </div>
                    <div class="col-md-12 searchinput">
                        <div class='input-group'>
                            <label class='input-group-addon' for='id_glossrelation_target'>{{searchform.target.label}}</label>
                            <input id="id_glossrelation_target" name='target' class='form-control'
                                   {% if searchform.target.value %}value='{{searchform.target.value}}' {% endif %}
                                   placeholder='{% blocktrans %}Begins with string{% endblocktrans %}'>
                        </div>
                    </div>
                </div>
                <div class="col-md-5 col-sm-6 searchinput">
                    <div class="col-md-12 searchinput">
                       <div class="input-group">
                           <label class="input-group-addon" for="id_tags">{{searchform.tags.label}}</label>
                           {% bootstrap_field searchform.tags show_label=False bound_css_class="not-bound" %}
                       </div>
                    </div>
                </div>
            </div>
        </div>
        <hr class="searchform-separator">
        <div class='btn-group'>
            <input class='btn btn-primary' type='submit' name='submit' value='{% blocktrans context "search-button" %}Search{% endblocktrans %}'>
            <input class='btn btn-default' type='submit' onclick="clearForm(document.adminsearch);" value='{% blocktrans %}Reset{% endblocktrans %}'>
        </div>

        <div class='form-group' id='paginate_by'>
            {# Translators: How many results to fit per page  #}
            <label for='paginate_by'>{% blocktrans %}Results per page{% endblocktrans %}</label>
            <select class='form-control' name="paginate_by">
                <option{% if paginator.per_page == 1000 %} selected{% endif %}>1000</option>
                <option{% if paginator.per_page == 500 %} selected{% endif %}>500</option>
                <option{% if paginator.per_page == 100 %} selected{% endif %}>100</option>
                <option{% if paginator.per_page == 50 %} selected{% endif %}>50</option>
                <option{% if paginator.per_page == 25 %} selected{% endif %}>25</option>
                <option{% if paginator.per_page == 10 %} selected{% endif %}>10</option>
            </select>
        </div>
    </form>
</div>
{% if object_list %}
<nav aria-label="{% blocktrans %}Page navigation top{% endblocktrans %}">
    {% include "dictionary/paginate.html" %}
</nav>
<table class='table table-condensed'>
    <thead>
        <tr>
            <th>{% blocktrans %}Source Gloss{% endblocktrans %} <a href="?search={{request.GET.search}}{% for key,value in request.GET.items %}{% if not key  == 'search' and not key == 'order' %}&{{ key }}={{ value }}{% endif %}{% endfor %}{% if order == 'source' or request.GET.order == 'source' %}&order=-source{% else %}&order=source{% endif %}">
                <span class="{% if request.GET.order == "-source" %}glyphicon glyphicon-sort-by-alphabet{% else %}glyphicon glyphicon-sort-by-alphabet-alt{% endif %}" aria-hidden="true"></span></a></th>
            <th>{% blocktrans %}Target Gloss{% endblocktrans %} <a href="?search={{request.GET.search}}{% for key,value in request.GET.items %}{% if not key  == 'search' and not key == 'order' %}&{{ key }}={{ value }}{% endif %}{% endfor %}{% if order == 'target' or request.GET.order == 'target' %}&order=-target{% else %}&order=target{% endif %}">
                <span class="{% if request.GET.order == "-target" %}glyphicon glyphicon-sort-by-alphabet{% else %}glyphicon glyphicon-sort-by-alphabet-alt{% endif %}" aria-hidden="true"></span></a></th>
            <th>{% blocktrans %}Relation type{% endblocktrans %}</th>
        </tr>
    </thead>
    <tbody>
    {% for glossrelation in object_list %}
        {# Here we decide/change the row background colors #}
        <tr>

            <td><span class="dataset-{{glossrelation.source.dataset.id}}-color label label-default">{{ glossrelation.source.dataset }}</span>
                <a href="{% url 'dictionary:admin_gloss_view' pk=glossrelation.source.pk %}"
                   data-thumbnail-src="{% if glossrelation.source.glossvideo_set.all.0.posterfile %}{{glossrelation.source.glossvideo_set.all.0.posterfile.url}}{% endif %}"
                   data-video-src="{% if glossrelation.source.glossvideo_set.all.0.videofile %}{{ glossrelation.source.glossvideo_set.all.0.videofile.url }}"
                   data-content-type="{{ glossrelation.source.glossvideo_set.all.0.get_content_type}}{% endif %}">{{glossrelation.source}}</a></td>
            <td><span class="dataset-{{glossrelation.target.dataset.id}}-color label label-default">{{ glossrelation.target.dataset }}</span>
                <a href="{% url 'dictionary:admin_gloss_view' pk=glossrelation.target.pk %}"
                   data-thumbnail-src="{% if glossrelation.target.glossvideo_set.all.0.posterfile %}{{glossrelation.target.glossvideo_set.all.0.posterfile.url}}{% endif %}"
                   data-video-src="{% if glossrelation.target.glossvideo_set.all.0.videofile %}{{ glossrelation.target.glossvideo_set.all.0.videofile.url }}"
                   data-content-type="{{ glossrelation.target.glossvideo_set.all.0.get_content_type}}{% endif %}">{{glossrelation.target}}</a></td>
            <td>{% for tag in glossrelation.cached_tags %}<span class='tag'>{{ tag }}</span>{% endfor %}</td>
        </tr>
    {% endfor %}
  </tbody>
</table>
<nav aria-label="{% blocktrans %}Page navigation bottom{% endblocktrans %}">
    {% include "dictionary/paginate.html" %}
</nav>
{% endif %}
{% endblock %}

signbank/dictionary/templates/dictionary/manage_lexicons.html
{% extends "baselayout.html" %}
{% load i18n %}
{% load bootstrap3 %}
{% load static %}
{% block bootstrap3_title %}{% blocktrans %}Manage lexicons{% endblocktrans %} | {% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <h2>{% blocktrans %}Manage lexicons{% endblocktrans %}</h2>
        <p>{% blocktrans %}On this page you can see all the lexicons available on this Signbank. You can view the Lexicons and apply for access to Lexicons.{% endblocktrans %}</p>
        <h3>{% blocktrans %}You have access to the following Lexicons{% endblocktrans %}</h3>
        {% for obj in has_permissions %}
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title" style="display:inline;"><span class="dataset-{{obj.id}}-color label label-default">{{obj.public_name}}</span></h3>
                {{obj.signlanguage}} ({{obj.signlanguage.language_code_3char}})
            </div>
            <div class="panel-body">
                <div class="well well-sm">
                    <h4><span class="glyphicon glyphicon-ok text-success" aria-hidden="true"></span> {% blocktrans %}Permissions?{% endblocktrans %}</h4>
                    <h4><span class="glyphicon glyphicon-{% if obj.is_public %}ok text-success{% else %}remove text-danger{% endif %}" aria-hidden="true"></span> {% blocktrans %}Public?{% endblocktrans %}</h4>
                </div>
                <h3>{% blocktrans %}Description{% endblocktrans %}</h3>
                    <p>{% autoescape off %}{{obj.description}}{% endautoescape %}</p>
                <h3>{% blocktrans %}Copyright{% endblocktrans %}</h3>
                    <p>{{obj.copyright}}</p>
                <h3>{% blocktrans %}ECV (externally controlled vocabulary){% endblocktrans %} <small>{% blocktrans %}A vocabulary for ELAN{% endblocktrans %}</small></h3>
                {% if obj.is_public %}<p>{% blocktrans %}Public ECV{% endblocktrans %}: <a href="https://{{ current_site_domain }}{% url 'dictionary:public_gloss_list_xml' obj.id %}">
                    https://{{ current_site_domain }}{% url 'dictionary:public_gloss_list_xml' obj.id %}</a></p>
                {% endif %}
                    <p>{% blocktrans %}Advanced ECV{% endblocktrans %}: <a href="https://{{ current_site_domain }}{% url 'dictionary:gloss_list_xml' obj.id %}">
                    https://{{ current_site_domain }}{% url 'dictionary:gloss_list_xml' obj.id %}</a></p>
                {% if user.is_superuser %}
                <h3>{% blocktrans %}Users with permissions{% endblocktrans %}</h3>
                <ul>{% for user in obj.users_with_perms.all %}
                    <li><a href="{{user.get_absolute_url}}">{{user}} ({{user.first_name}} {{user.last_name}})</a></li>
                     {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>
        {% empty %}
        <p>{% blocktrans %}You don't seem to have access to any Lexicons.{% endblocktrans %}</p>
        {% endfor %}
        <h3>{% blocktrans %}You do NOT have access to the following Lexicons{% endblocktrans %}</h3>
        {% for obj in no_permissions %}
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title" style="display:inline;"><span class="dataset-{{obj.id}}-color label label-default">{{obj.public_name}}</span></h3>
                {{obj.signlanguage}} ({{obj.signlanguage.language_code_3char}})
            </div>
            <div class="panel-body">
                <div class="well well-sm">
                    <h4>{% blocktrans %}Permissions?{% endblocktrans %} <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span></h4>
                    <h4>{% blocktrans %}Public?{% endblocktrans %} <span class="glyphicon glyphicon-{% if obj.is_public %}ok text-success{% else %}remove text-danger{% endif %}" aria-hidden="true"></span></h4>
                    <form action="{% url 'dictionary:apply_lexicon_permissions' %}" method="POST" style="display:inline;">{% csrf_token %}
                        <input type="hidden" name="dataset" value="{{obj.id}}">
                        <button type="submit" class="btn btn-primary btn-sm">{% blocktrans %}Apply for permissions{% endblocktrans %}</button>
                    </form>
                </div>
                <h3>{% blocktrans %}Description{% endblocktrans %}</h3>
                    <p>{% autoescape off %}{{obj.description}}{% endautoescape %}</p>
                <h3>{% blocktrans %}Copyright{% endblocktrans %}</h3>
                    <p>{{obj.copyright}}</p>
                {% if obj.is_public %}
                <h3>{% blocktrans %}ECV (externally controlled vocabulary){% endblocktrans %} <small>{% blocktrans %}A vocabulary for ELAN{% endblocktrans %}</small></h3>
                    <p>{% blocktrans %}Public ECV{% endblocktrans %}: <a href="https://{{ current_site_domain }}{% url 'dictionary:public_gloss_list_xml' obj.id %}">
                    https://{{ current_site_domain }}{% url 'dictionary:public_gloss_list_xml' obj.id %}</a></p>
                {% endif %}
            </div>
        </div>
        {% empty %}
        <p>{% blocktrans %}You seem to have access to all existing Lexicons.{% endblocktrans %}</p>
        {% endfor %}
    </div>
</div>
{% endblock %}