signbank/dictionary/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path
from django.views.generic.base import RedirectView

# Views
from . import adminviews, delete, publicviews, update, views

# Application namespace
app_name = 'dictionary'

urlpatterns = [
    # Public views for dictionary
    path('', publicviews.GlossListPublicView.as_view(), name='public_gloss_list'),
    path('gloss/<int:pk>', publicviews.GlossDetailPublicView.as_view(),
         name='public_gloss_view'),
    # Support old URLs, redirect them to new URLs.
    path('public/gloss/',
         RedirectView.as_view(pattern_name='dictionary:public_gloss_list', permanent=False)),
    path('public/gloss/<int:pk>',
         RedirectView.as_view(pattern_name='dictionary:public_gloss_view', permanent=False)),

    # Advanced search page
    path('advanced/', permission_required('dictionary.search_gloss')
         (adminviews.GlossListView.as_view()), name='admin_gloss_list'),

    # Main views for dictionary search page and gloss detail page, these used to be 'admin' views
    path('advanced/list/', permission_required('dictionary.search_gloss')
         (adminviews.GlossListView.as_view())),
    path('advanced/gloss/<int:pk>', permission_required('dictionary.search_gloss')
         (adminviews.GlossDetailView.as_view()), name='admin_gloss_view'),

    # GlossRelation search page
    path('advanced/glossrelation/', permission_required('dictionary.search_gloss')
         (adminviews.GlossRelationListView.as_view()), name='search_glossrelation'),
    # Redirect old URL
    path('search/glossrelation/', permission_required('dictionary.search_gloss')
         (RedirectView.as_view(pattern_name='dictionary:search_glossrelation', permanent=False))),

    # Manage lexicons
    path('lexicons/', login_required(views.ManageLexiconsListView.as_view()),
         name='manage_lexicons'),
    # Apply for lexicon permissions
    path('lexicons/apply/', login_required(views.ApplyLexiconPermissionsFormView.as_view()),
         name='apply_lexicon_permissions'),

    # Create
    path('advanced/gloss/create/', views.create_gloss, name='create_gloss'),

    # Urls used to update data
    path('update/gloss/<int:glossid>',
         update.update_gloss, name='update_gloss'),
    path('update/tag/<int:glossid>',
         update.add_tag, name='add_tag'),
    path('update/relation/',
         update.add_relation, name='add_relation'),
    path('update/relationtoforeignsign/',
         update.add_relationtoforeignsign, name='add_relationtoforeignsign'),
    path('update/morphologydefinition/',
         update.add_morphology_definition, name='add_morphologydefinition'),
    path('update/glossrelation/',
         update.gloss_relation, name='add_glossrelation'),

    path('advanced/delete/glossurl/<int:glossurl>',
         delete.glossurl, name='delete_glossurl'),

    path('update/lemma/<int:glossid>',
         update.add_lemma, name='add_lemma'),


    # CSV import urls
    path('advanced/import/csv/',
         update.import_gloss_csv, name='import_gloss_csv'),
    path('advanced/import/csv/confirm/',
         update.confirm_import_gloss_csv, name='confirm_import_gloss_csv'),

    # AJAX urls
    path('ajax/keyword/<str:prefix>',
         views.keyword_value_list),
    path('ajax/gloss/<str:prefix>',
         adminviews.gloss_ajax_complete, name='gloss_complete'),
    path('ajax/searchresults/',
         adminviews.gloss_ajax_search_results, name='ajax_search_results'),

    # XML ecv (externally controlled vocabulary) export for ELAN
    path('ecv/<int:dataset_id>',
         adminviews.gloss_list_xml, name='gloss_list_xml'),
    # Public ECV's
    path('public-ecv/<int:dataset_id>',
         publicviews.public_gloss_list_xml, name='public_gloss_list_xml'),

    path('csv/<int:dataset_id>',
         permission_required('dictionary.search_gloss')(adminviews.gloss_list_csv), name='gloss_list_csv'),

    # Network Graph of GlossRelations
    path('network-graph/',login_required(views.network_graph), name='network_graph'),
]

signbank/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.urls import path, re_path, include
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib import admin
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.views.static import serve

# Views
from django_registration.backends.activation.views import RegistrationView
from .dictionary.adminviews import GlossListView
from .tools import infopage
from django.contrib.flatpages import views as flatpages_views
from .comments import edit_comment, latest_comments, latest_comments_page, CommentListView, remove_tag
import notifications.urls
from .sitemaps import GlossSitemap, SignbankFlatPageSiteMap, StaticViewSitemap
# Forms
from .customregistration.forms import CustomUserForm

# Application namespace
app_name = 'signbank'

urlpatterns = [
    # Root page
    path('', flatpages_views.flatpage, {'url': '/'}, name='root_page'),

    path('sitemap.xml', sitemap, {'sitemaps': {'flatpages': SignbankFlatPageSiteMap,
                                                  'static': StaticViewSitemap,
                                                  'gloss': GlossSitemap, }},
        name='django.contrib.sitemaps.views.sitemap'),

    # This allows to change the translations site language
    path('i18n/', include('django.conf.urls.i18n')),

    # Include dictionary/, and video/ urls
    path('dictionary/',
        include('signbank.dictionary.urls', namespace='dictionary')),
    path('video/', include('signbank.video.urls', namespace='video')),

    # We used to have this url, keeping it in order to support old urls.
    path('signs/search/', permission_required('dictionary.search_gloss')(GlossListView.as_view()),
        name='sign_search'),

    # Registration urls for login, logout, registration, activation etc.
    path('accounts/register/', RegistrationView.as_view(form_class=CustomUserForm), name='django_registration_register',),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    # Django-contrib-comments urls
    path('comments/', include('django_comments.urls')),
    # Custom functionality added to comments app. Comment editing.
    path('comments/update/<int:id>/', login_required(edit_comment, login_url='/accounts/login/')),
    # Feed for latest comments.
    path('comments/latest/', permission_required('dictionary.search_gloss')(latest_comments),
        name='latest_comments'),
    # Page showing feed for latest comments. Count indicates how many comments to show.
    path('comments/latest/<int:count>/', permission_required('dictionary.search_gloss')(latest_comments_page),
        name='latest_comments_page'),
    path('comments/search/', permission_required('dictionary.search_gloss')(CommentListView.as_view()),
        name='search_comments'),
    path('comments/removetag/', permission_required('dictionary.search_gloss')(remove_tag),
        name='remove-comment-tag'),

    # Notifications urls
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # Admin urls
    path('admin/doc/',
        include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),

    # Summernote urls, Summernote is the WYSIWYG editor currently used in Signbank
    path('summernote/', include('django_summernote.urls')),

    # Infopage, where we store some links and statistics
    path('info/', infopage, name='infopage'),
]
if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]
    try:
        import debug_toolbar
        # Add debug_toolbar when DEBUG=True, also add static+media folders when in development.
        # DEBUG should be False when in production!
        urlpatterns += [
            path('__debug__/', include(debug_toolbar.urls)),
        ]
    except (ImportError, ModuleNotFoundError):
        pass

# This is a catchall pattern, will try to match the rest of the urls with flatpages.
urlpatterns += [re_path('(?P<url>.*/)', flatpages_views.flatpage), ]  # Keep this as the last URL in the file!

signbank/video/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.urls import path

# Views
from . import views

# Application namespace
app_name = 'video'

urlpatterns = [
    path('<int:videoid>/', views.video_view, name='glossvideo'),
    path('poster/<int:videoid>', views.poster_view, name='glossvideo_poster'),
    path('upload/', views.upload_glossvideo_view, name='upload_glossvideo'),
    path('upload/gloss/', views.upload_glossvideo_gloss_view,
         name='upload_glossvideo_gloss'),
    path('upload/recorded/', views.add_recorded_video_view,
         name='add_recorded_video'),
    # View to upload multiple videos with no foreign key to gloss.
    path('add/', views.addvideos_formview, name='upload_videos'),
    # View that shows a list of glossvideos with no foreign key to gloss, user can add fk to gloss for glossvideos.
    path('uploaded/', views.uploaded_glossvideos_listview, name='manage_videos'),
    # View that updates a glossvideo
    path('update/', views.update_glossvideo_view, name='glossvideo_update'),
    # View that handles the upload of poster file
    path('add/poster', views.add_poster_view, name='add_poster'),
    # Change priority of video
    path('order/', views.change_glossvideo_order,
         name='change_glossvideo_order'),
    # Change publicity of video
    path('publicity/', views.change_glossvideo_publicity,
         name='change_glossvideo_publicity'),

    path('csv', views.export_glossvideos_csv, name='export_glossvideos_csv')
]

templates/baselayout.html
<!DOCTYPE html>
{% load bootstrap3 %}
{% load stylesheet %}
{% load i18n %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{LANGUAGE_CODE|default:'en'}}">
  <head>
    <title>{% block bootstrap3_title %}{% endblock %}{% blocktrans %}NZSL Signbank{% endblocktrans %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">

    {% block metadesc %}<meta name="description" content="{% blocktrans context 'meta' %}NZSL Signbank is a lexical database of Finnish Sign Language (FinSL) and Finland-Swedish Sign Language (FinSSL).{% endblocktrans %}">{% endblock %}

    {% block ogimage %}<meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'img/signbank_logo_ympyra1_sininen-compressor.png' %}">{% endblock %}
    {% block ogdesc %}<meta property="og:description" content="{% blocktrans context 'meta' %}NZSL Signbank is a lexical database of Finnish Sign Language (FinSL) and Finland-Swedish Sign Language (FinSSL).{% endblocktrans %}">{% endblock %}
    {% block metatitles %}
    <meta property="og:title" content="{% blocktrans context 'meta' %}NZSL Signbank{% endblocktrans %}">
    <meta name="twitter:title" content="{% blocktrans context 'meta' %}NZSL Signbank{% endblocktrans %}">
    {% endblock %}
<script type="application/ld+json">
// Structured data for Google
// Logo
{
  "@context": "http://schema.org",
  "@type": "Organization",
  "url": "{{ request.scheme }}://{{ request.get_host }}",
  "logo": "{{ request.scheme }}://{{ request.get_host }}{% static 'img/signbank_logo_ympyra1_sininen-compressor.png' %}"
}
// Sitelinks searchbox
{
  "@context": "http://schema.org",
  "@type": "WebSite",
  "url": "{{ request.scheme }}://{{ request.get_host }}",
  "potentialAction": {
    "@type": "SearchAction",
    "target": "{{ request.scheme }}://{{ request.get_host }}{% url 'dictionary:public_gloss_list' %}?keyword={search_term_string}",
    "query-input": "required name=search_term_string"
  }
}
</script>
    {% block structureddata %}{% endblock %}
    <link rel="stylesheet" media="screen" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/signbank.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dataset.css' %}">
    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
{% if not user.is_authenticated %}
    {% include "policyconsent.html" %}
{% endif %}
    {% block extrahead %}{% endblock %}
  </head>
  <body>
    <div id="wrap">
        <div class="container">
            <div id="leftcontentborder"></div>
            <div id="rightcontentborder"></div>
            <header id="header">{# Translators: Site title #}
                <div class="headerlogo">
                    <h1>
                        <a href="{% url 'root_page' %}" title="{% blocktrans %}NZSL Signbank{% endblocktrans %}">
                            <img id="logoheadersignbank"
                                 src="{% static 'img/signbank_logo_laatikko_valkoinen_crop-compressor.png' %}"
                                 alt="{% blocktrans %}NZSL Signbank{% endblocktrans %}">
                        </a>
                    </h1>
                </div>
                <div id="langbar">{% include "langbar.html" %}</div>
            </header>
            <div id="menu">
                {% include "menu.html" %}
            </div>
            {% bootstrap_messages %}
            <main role="main">
            {% block content %}{% blocktrans %}(No content){% endblocktrans %}{% endblock %}
            </main>
        </div>
    </div>
    <footer id="footer">
       <div id="footercontainer" class="container">
            <div class="footerbg">
            </div>
       </div>
    </footer>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

<script>
$('a.close').on('click', function(event){
    event.preventDefault();
    event.stopPropagation();
    var parent = $(this).parent();
    $.get(event.currentTarget.href).done(function () {
        parent.remove();
        var badge = $('#live_notify_badge');
        var val = parseInt(badge.text())
        badge.text(val - 1);
        if (val - 1 <= 0) {
            $('button#notifications-list').removeClass('btn-danger');
        }
    });
});
$('a#notifications_mark_all_read').on('click', function(event){
    event.preventDefault();
    event.stopPropagation();
    $.get(event.currentTarget.href).done(function () {
        $('div.notification').remove();
        var badge = $('#live_notify_badge');
        badge.text("0");
        $('button#notifications-list').removeClass('btn-danger');
    });
});
</script>
    {% block extrajs %}{% endblock %}
  </body>
</html>

templates/infopage.html
{% extends 'baselayout.html' %}
{% load stylesheet %}
{% load bootstrap3 %}
{% load i18n %}
{% block bootstrap3_title %}{% blocktrans %}Links and Statistics{% endblocktrans %} | {% endblock %}
{% block content %}
    {% if perms.dictionary.search_gloss %}
    <div id="infopage" class="container-fluid">
        {# Translators: Header for infopage #}
        <div class="row">
            <div class="col-md-6">
                <h2>{% blocktrans %}Links and statistics{% endblocktrans %}</h2>
                <p>{% blocktrans trimmed %}On this page you can find numerical data about the database, and
                    links to externally controlled vocabularies to be used in ELAN.{% endblocktrans %}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{% blocktrans %}All lexicons{% endblocktrans %}</h3>
                    </div>
                    <div class="panel-body">
                    <table class="table table-bordered">
                        <tr>
                            <td>{% blocktrans %}Gloss count{% endblocktrans %}</td>
                            <td>{{context.gloss_count}}</td>
                        </tr>
                         <tr>
                            <td>{% blocktrans %}Glosses with video{% endblocktrans %}</td>
                            <td>{{context.glosses_with_video}}</td>
                        </tr>
                        <tr>
                            <td>{% blocktrans %}Video count{% endblocktrans %}</td>
                            <td>{{context.glossvideo_count}}</td>
                        </tr>
                        <tr>
                            <td>{% blocktrans %}Videos not connected to a Gloss{% endblocktrans %}</td>
                            <td>{{context.glossless_video_count}}</td>
                        </tr>
                        <tr>
                            <td>{% blocktrans %}Videos with poster image{% endblocktrans %}</td>
                            <td>{{context.glossvideo_poster_count}}</td>
                        </tr>
                        <tr>
                            <td>{% blocktrans %}Videos without poster image{% endblocktrans %}</td>
                            <td>{{context.glossvideo_noposter_count}}</td>
                        </tr>
                    </table>
                    <h4>{% blocktrans %}Translation equivalents{% endblocktrans %}:</h4>
                    <table class="table table-bordered">
                        {% for language in context.languages %}
                        <tr>
                            <td>{{language}}</td>
                            <td>{{language.translation_set.count}}</td>
                        </tr>
                        {% endfor %}
                    </table>
                    </div>
                </div>
            </div>
            <div id="ELANinfo" class="col-md-6">
                <div class="well">
                    <h4>{% blocktrans %}ELAN externally controlled vocabulary links{% endblocktrans %}</h4>
                    <ul>
                        {% for dataset in datasets %}
                        <li style="list-style-type:none;margin-bottom:2px;">
                            <span class="dataset-{{dataset.dataset.id}}-color label label-default">
                                {{dataset.dataset}}</span>
                            <a href="http://{{ request.get_host }}/dictionary/ecv/{{ dataset.dataset.pk }}"
                               target="_blank">
                                http://{{ request.get_host }}/dictionary/ecv/{{ dataset.dataset.pk }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    <h4>{% blocktrans %}Signbank Wiki{% endblocktrans %}
                        <small>{% blocktrans %}Help and tutorials{% endblocktrans %}</small></h4>
                    <p><a href ="https://github.com/Signbank/FinSL-signbank/wiki" target="_blank">
                        https://github.com/Signbank/FinSL-signbank/wiki</a></p>
                </div>
            </div>
            {% if user.is_staff and context.psql_db_size and context.psql_db_size_pretty and context.psql_db_usage %}
            {# This shows the usage of database quota, works only if you use postgresql #}
            <div class="col-md-6">
                <h4>{% blocktrans %}Database storage space usage{% endblocktrans %}</h4>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: {{context.psql_db_usage}}%;">
                    {{context.psql_db_usage}}%
                  </div>
                </div>
                <p>{% blocktrans %}Space used{% endblocktrans %}: {{context.psql_db_size_pretty}}</p>
            </div>
            {% endif %}
            {% if request.user.is_staff and context.problems %}
            <div class="col-md-6">
                <h4>{% blocktrans %}Files that do not exist{% endblocktrans %} ({{context.problems|length}}): </h4>
                <ul>
                {% for p in context.problems %}
                    <li><a href="{% url "admin:video_glossvideo_change" p.id %}">{{p.type}} {{p.id}}, {{p.file}}</a></li>
                {% endfor %}
                </ul>
            </div>
            {% endif %}
        </div>
        <div class="row">
            {% for dataset in datasets %}
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{% blocktrans %}Lexicon{% endblocktrans %}
                            <span class="dataset-{{dataset.dataset.id}}-color label label-default">{{dataset.dataset}}</span></h3>
                    </div>
                    <div class="panel-body">
                        <table class="table table-bordered">
                            <tr>
                                <td>{% blocktrans %}Gloss count{% endblocktrans %}</td>
                                <td>{{dataset.gloss_count}}</td>
                            </tr>
                             <tr>
                                <td>{% blocktrans %}Glosses with video{% endblocktrans %}</td>
                                <td>{{dataset.glosses_with_video}}</td>
                            </tr>
                            <tr>
                                <td>{% blocktrans %}Video count{% endblocktrans %}</td>
                                <td>{{dataset.glossvideo_count}}</td>
                            </tr>
                            <tr>
                                <td>{% blocktrans %}Videos not connected to a Gloss{% endblocktrans %}</td>
                                <td>{{dataset.glossless_video_count}}</td>
                            </tr>
                            <tr>
                                <td>{% blocktrans %}Videos with poster image{% endblocktrans %}</td>
                                <td>{{dataset.glossvideo_poster_count}}</td>
                            </tr>
                            <tr>
                                <td>{% blocktrans %}Videos without poster image{% endblocktrans %}</td>
                                <td>{{dataset.glossvideo_noposter_count}}</td>
                            </tr>
                        </table>
                        <h4>{% blocktrans %}Translation equivalents{% endblocktrans %}:</h4>
                        <table class="table table-bordered">
                            {% for language, translation_count in dataset.translations %}
                            <tr>
                                <td>{{language}}</td>
                                <td>{{translation_count}}</td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% else %}
    {# Translators: Message that appears if user doesn't have proper user rights to view this page. #}
    <p>{% blocktrans %}You do not have sufficient user rights to view this page.{% endblocktrans %}</p>
    {% endif %}
{% endblock %}

templates/menu.html
{% load i18n %}
{% load flatpages %}
<nav id="navbar" class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
            {# Translators: Button to toggle navigation #}
            <span class="sr-only">{% blocktrans %}Toggle navigation{% endblocktrans %}</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><a href="/">{% blocktrans %}Home{% endblocktrans %}</a></li>
        {% get_flatpages '/about/' as about_pages %}
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    {% blocktrans %}About{% endblocktrans %} <span class="caret"></span></a>
                <ul class="dropdown-menu">
            {% for page in about_pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}

                <li><a href="https://github.com/Signbank/FinSL-signbank/wiki" target="_blank">
                    {% blocktrans %}Wiki{% endblocktrans %}</a></li>
               </ul>
            </li>

            <li><a href="{% url "dictionary:public_gloss_list" %}">{% blocktrans %}Signs{% endblocktrans %}</a></li>

        {% if user.is_authenticated %}
            {% if perms.dictionary.search_gloss %}
            <li><a href="{% url "dictionary:admin_gloss_list" %}">{% blocktrans context "menu-link" %}Advanced search{% endblocktrans %}</a></li>
            <li><a href="{% url 'dictionary:search_glossrelation' %}">{% blocktrans %}Search relations{% endblocktrans %}</a></li>
            {% endif %}
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    {% blocktrans %}Manage{% endblocktrans %} <span class="caret"></span></a>
                <ul class="dropdown-menu">
                {% if perms.dictionary.add_gloss and perms.dictionary.change_gloss %}
                    <li><a href="{% url 'dictionary:create_gloss' %}">{% blocktrans %}Create gloss{% endblocktrans %}</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'video:upload_videos' %}">{% blocktrans %}Upload videos{% endblocktrans %}</a></li>
                    <li><a href="{% url 'video:manage_videos' %}">{% blocktrans %}Manage uploaded videos{% endblocktrans %}</a></li>
                    <li role="separator" class="divider"></li>
                    {% if perms.dictionary.import_csv %}
                    <li><a href="{% url 'dictionary:import_gloss_csv' %}">{% blocktrans %}CSV import{% endblocktrans %}</a></li>
                    {% endif %}
                    <li><a href="{% url 'infopage' %}">{% blocktrans %}Links and statistics{% endblocktrans %}</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'latest_comments_page' count='20' %}">{% blocktrans %}Latest comments{% endblocktrans %}</a></li>
                    <li><a href="{% url 'search_comments' %}">{% blocktrans %}Search comments{% endblocktrans %}</a></li>
                    <li role="separator" class="divider"></li>
                {% endif %}
                    <li><a href="{% url 'dictionary:manage_lexicons' %}">{% blocktrans %}Lexicons{% endblocktrans %}</a></li>
                    <li><a href="{% url 'dictionary:network_graph' %}">{% blocktrans %}Network Graphs{% endblocktrans %}</a></li>
                </ul>
            </li>
        {% endif %}
        </ul>
        <form class="navbar-form navbar-right" role="search" id="menusearch" name="menusearch" method="get"
              action="{% url 'dictionary:public_gloss_list' %}">
            <div class="input-group">
                {# Translators: Placeholder text in a search textfield #}
                <input class="form-control" placeholder="{% blocktrans %}Search gloss{% endblocktrans %}" type="text"
                       name="gloss" value="{% if searchform.gloss.value %}{{ searchform.gloss.value }}{% endif %}"
                       maxlength="50">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default">{% blocktrans context "search-button" %}Search{% endblocktrans %}</button>
                </span>
            </div>
            {# Translators: Submit button (press to search) #}

        </form>
    </div>
    <!-- /.navbar-collapse -->
</nav>